import { createClient } from '@/lib/supabase/client'
export type PautaStatus = 'aberta' | 'em_producao' | 'em_revisao' | 'publicada' | 'cancelada'
export interface Pauta { id: string; plataforma_id: string; titulo: string; briefing: string; prazo: string | null; status: PautaStatus }
export interface Texto { id: string; pauta_id: string; titulo: string; conteudo: string; status: 'rascunho' | 'revisao' | 'aprovado' | 'publicado' }
export async function fetchRedacao(platformId: string) { const sb = createClient(); const [pautas, textos] = await Promise.all([sb.from('ruja_redacao_pautas').select('*').eq('plataforma_id', platformId).order('created_at', { ascending: false }), sb.from('ruja_redacao_textos').select('*').eq('plataforma_id', platformId).order('created_at', { ascending: false })]); if (pautas.error) throw pautas.error; if (textos.error) throw textos.error; return { pautas: (pautas.data ?? []) as Pauta[], textos: (textos.data ?? []) as Texto[] } }
export async function createPauta(input: { plataforma_id: string; titulo: string; briefing: string; prazo: string | null }) { const sb = createClient(); const { data: { user } } = await sb.auth.getUser(); if (!user) throw new Error('Sessão expirada. Faça login novamente.'); const { error } = await sb.from('ruja_redacao_pautas').insert({ ...input, criado_por: user.id }); if (error) throw error }
export async function updatePautaStatus(id: string, status: PautaStatus) { const { error } = await createClient().from('ruja_redacao_pautas').update({ status, updated_at: new Date().toISOString() }).eq('id', id); if (error) throw error }
export async function createTexto(input: { plataforma_id: string; pauta_id: string; titulo: string; conteudo: string }) { const sb = createClient(); const { data: { user } } = await sb.auth.getUser(); if (!user) throw new Error('Sessão expirada. Faça login novamente.'); const { error } = await sb.from('ruja_redacao_textos').insert({ ...input, autor_id: user.id }); if (error) throw error }
export async function updateTextoStatus(id: string, status: Texto['status']) { const { error } = await createClient().from('ruja_redacao_textos').update({ status, updated_at: new Date().toISOString() }).eq('id', id); if (error) throw error }
